name: Deploy Web

on:
  push:
    branches: ["xiangbingcai"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy web files to Aliyun
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          port: 22
          source: "web/*"
          target: "/opt/JARVIS/web"
          strip_components: 1
      
      - name: Copy ai files to Aliyun
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          port: 22
          source: "ai/*"
          target: "/opt/JARVIS/ai"
          strip_components: 1
      


      - name: Deploy to Aliyun
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          port: 22
          script: |
            cd /opt/JARVIS/web
            pnpm install
            pnpm run build
            pm2 restart web || pm2 start npm --name "web" -- start

      - name: Install Python dependencies And Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }} 
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}  
          port: 22
          script: |
            cd /opt/JARVIS/ai
            python3 -m venv venv
            source venv/bin/activate
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
            python3 main.py 
         






